/* Override TBL defaults for BPNode — needs more tables and larger sizes */
#ifndef CFE_TBL_PLATFORM_CFG_H
#define CFE_TBL_PLATFORM_CFG_H

#define CFE_PLATFORM_TBL_MAX_NUM_TABLES          128
#define CFE_PLATFORM_TBL_MAX_SNGL_TABLE_SIZE     16384
#define CFE_PLATFORM_TBL_MAX_DBL_TABLE_SIZE      16384
#define CFE_PLATFORM_TBL_BUF_MEMORY_BYTES        524288
#define CFE_PLATFORM_TBL_MAX_NUM_HANDLES         256
#define CFE_PLATFORM_TBL_MAX_SIMULTANEOUS_LOADS   4
#define CFE_PLATFORM_TBL_MAX_NUM_VALIDATIONS     10
#define CFE_PLATFORM_TBL_MAX_CRITICAL_TABLES     32
#define CFE_PLATFORM_TBL_START_TASK_PRIORITY     70
#define CFE_PLATFORM_TBL_START_TASK_STACK_SIZE   CFE_PLATFORM_ES_DEFAULT_STACK_SIZE
#define CFE_PLATFORM_TBL_VALID_SCID_COUNT        0
#define CFE_PLATFORM_TBL_VALID_PRID_COUNT        0
#define CFE_PLATFORM_TBL_DEFAULT_REG_DUMP_FILE   "/ram/cfe_tbl_reg.log"

#endif
