[package]
name = "hardy-tcpcl-fuzz"
version = "0.0.0"
publish = false
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
hardy-tcpcl = { path = ".." }
config = { version = "0.14.0", features = ["toml"] }
tokio-util = "0.7.11"
tokio = { version = "1.39.3", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "time",
] }

[[bin]]
name = "passive"
path = "fuzz_targets/passive.rs"
test = false
doc = false
bench = false
