#![no_main]

//! Fuzz target for the TCPCLv4 connector (active session establishment).
//!
//! Listens on localhost, accepts a connection from the CLA's `connect()`,
//! writes fuzz-generated bytes as the "server" response, and verifies the
//! implementation doesn't panic.

use hardy_tcpclv4_fuzz::*;
use libfuzzer_sys::fuzz_target;
use std::sync::OnceLock;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

static RT: OnceLock<tokio::runtime::Runtime> = OnceLock::new();
static CLA: OnceLock<std::sync::Arc<hardy_tcpclv4::Cla>> = OnceLock::new();
static LISTENER: OnceLock<TcpListener> = OnceLock::new();

fn get_runtime() -> &'static tokio::runtime::Runtime {
    RT.get_or_init(|| {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("failed to create tokio runtime")
    })
}

fn get_cla() -> &'static std::sync::Arc<hardy_tcpclv4::Cla> {
    CLA.get_or_init(|| get_runtime().block_on(setup_connector()))
}

fn get_listener() -> &'static TcpListener {
    LISTENER.get_or_init(|| {
        get_runtime()
            .block_on(TcpListener::bind(fuzz_addr()))
            .expect("failed to bind fuzz listener")
    })
}

fuzz_target!(|data: &[u8]| {
    let cla = get_cla();
    let listener = get_listener();
    let local_addr = listener.local_addr().unwrap();

    get_runtime().block_on(async {
        // Timeout the entire iteration — the CLA retries connect up to 5
        // times with a 2s contact timeout, so 15s is generous.
        let _ = tokio::time::timeout(
            tokio::time::Duration::from_secs(15),
            run_iteration(data, cla, listener, &local_addr),
        )
        .await;
    });
});

async fn run_iteration(
    data: &[u8],
    cla: &std::sync::Arc<hardy_tcpclv4::Cla>,
    listener: &TcpListener,
    local_addr: &std::net::SocketAddr,
) {
    // Spawn the CLA connect attempt
    let cla = cla.clone();
    let addr = *local_addr;
    let connect_handle = tokio::task::spawn(async move {
        let _ = cla.connect(&addr).await;
    });

    // Accept one connection from the CLA and send fuzz data as "server"
    if let Ok(Ok((stream, _))) =
        tokio::time::timeout(tokio::time::Duration::from_secs(5), listener.accept()).await
    {
        let (mut rx, mut tx) = stream.into_split();

        // Drain anything the CLA sends in the background
        let drain = tokio::task::spawn(async move {
            let mut buf = [0u8; 4096];
            loop {
                match rx.read(&mut buf).await {
                    Ok(0) | Err(_) => break,
                    _ => {}
                }
            }
        });

        // Write fuzz data as the "server" response and close
        let _ = tx.write_all(data).await;
        let _ = tx.shutdown().await;

        let _ = drain.await;
    }

    let _ = connect_handle.await;
}
