#![no_main]

// Fuzz target for the TCPCLv4 connector (active session establishment).
//
// Listens on an ephemeral localhost port, accepts every connection the CLA's
// `connect()` opens (it retries up to 5 times), writes fuzz-generated bytes as
// the "server" response, and verifies the implementation doesn't panic.

use hardy_tcpclv4_fuzz::*;
use libfuzzer_sys::fuzz_target;
use std::sync::OnceLock;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

static RT: OnceLock<tokio::runtime::Runtime> = OnceLock::new();
// One CLA reused across all iterations. A completed session (which needs the
// fuzz data to contain a valid SESS_INIT — rare) leaves an entry in its
// connection registry between runs; accepted state drift, negligible against
// the cost of recreating the CLA per iteration.
static CLA: OnceLock<std::sync::Arc<hardy_tcpclv4::Cla>> = OnceLock::new();
static LISTENER: OnceLock<TcpListener> = OnceLock::new();
static LOCAL_ADDR: OnceLock<std::net::SocketAddr> = OnceLock::new();

fn get_runtime() -> &'static tokio::runtime::Runtime {
    RT.get_or_init(|| {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("failed to create tokio runtime")
    })
}

fn get_cla() -> &'static std::sync::Arc<hardy_tcpclv4::Cla> {
    CLA.get_or_init(|| get_runtime().block_on(setup_connector()))
}

fn get_listener() -> &'static TcpListener {
    LISTENER.get_or_init(|| {
        // Bind an ephemeral port: this target owns both ends and connects to the
        // listener's real local_addr(), so it needs no fixed or shared port.
        get_runtime()
            .block_on(TcpListener::bind((std::net::Ipv6Addr::LOCALHOST, 0)))
            .expect("failed to bind fuzz listener")
    })
}

fn get_local_addr() -> &'static std::net::SocketAddr {
    LOCAL_ADDR.get_or_init(|| {
        get_listener()
            .local_addr()
            .expect("failed to read listener local_addr")
    })
}

// Discard any connections sitting in the listener's accept queue without
// blocking. The listener is static, so a connection left queued (the backstop
// fired mid-iteration, or the connector's final attempt landed after
// `connect()` returned) would otherwise be served with the *next* iteration's
// fuzz data, breaking the input<->behaviour correlation.
async fn drain_accept_queue(listener: &TcpListener) {
    while let Some(stream) = std::future::poll_fn(|cx| {
        std::task::Poll::Ready(match listener.poll_accept(cx) {
            std::task::Poll::Ready(Ok((stream, _))) => Some(stream),
            std::task::Poll::Ready(Err(_)) | std::task::Poll::Pending => None,
        })
    })
    .await
    {
        drop(stream);
    }
}

fuzz_target!(|data: &[u8]| {
    let cla = get_cla();
    let listener = get_listener();
    let local_addr = get_local_addr();

    get_runtime().block_on(async {
        // Backstop the whole iteration. With every connection served promptly
        // (below) the connector finishes in milliseconds; this only caps a
        // pathological input. The connector's own worst case is ~5s (5 retries
        // x 1s contact timeout), so the backstop sits well clear of it — a
        // slow-unit report means a pathological input, not the normal retry
        // loop on a loaded runner.
        let _ = tokio::time::timeout(
            tokio::time::Duration::from_secs(10),
            run_iteration(data, cla, listener, local_addr),
        )
        .await;

        drain_accept_queue(listener).await;
    });
});

async fn run_iteration(
    data: &[u8],
    cla: &std::sync::Arc<hardy_tcpclv4::Cla>,
    listener: &TcpListener,
    local_addr: &std::net::SocketAddr,
) {
    // Run the CLA connect attempt (it retries internally, up to 5 times) in a
    // JoinSet: if the iteration backstop drops this future, dropping the set
    // aborts the task instead of detaching it to leak sockets and CLA state.
    let mut connect_task = tokio::task::JoinSet::new();
    let cla = cla.clone();
    let addr = *local_addr;
    connect_task.spawn(async move {
        let _ = cla.connect(&addr).await;
    });

    // Serve every connection the connector opens, so no attempt waits out its
    // contact timeout and each retry is exercised with the fuzz data. Both
    // select branches are cancel-safe: `accept()` loses no connection when the
    // other branch completes first, so neither needs pinning.
    loop {
        tokio::select! {
            // Connector finished (all retries done, or a session established).
            _ = connect_task.join_next() => break,
            accepted = listener.accept() => {
                let Ok((stream, _)) = accepted else { break };
                let (mut rx, mut tx) = stream.into_split();
                tokio::join!(
                    // Drain anything the CLA sends.
                    async {
                        let mut buf = [0u8; 4096];
                        loop {
                            match rx.read(&mut buf).await {
                                Ok(0) | Err(_) => break,
                                _ => {}
                            }
                        }
                    },
                    // Write fuzz data as the "server" response and close.
                    async {
                        let _ = tx.write_all(data).await;
                        let _ = tx.shutdown().await;
                    },
                );
            }
        }
    }
}
