use core::time::Duration;

use futures::{FutureExt, select_biased};
use hardy_bpv7::{bundle::Id, status_report::ReasonCode};

use super::*;
use crate::stream::{Receiver, Segment, concat_stream};

impl Dispatcher {
    /// Run Originate filter on an in-memory bundle (not yet stored).
    /// If the filter drops the bundle, Ok(None) is returned.
    /// If the filter passes or no filter is registered, returns Ok(Some((bundle, data))).
    ///
    /// This is a pure in-memory operation - no persistence occurs here.
    /// The caller is responsible for storing the bundle after filtering.
    async fn run_originate_filter(
        &self,
        bundle: bundle::Bundle,
        data: Bytes,
    ) -> Result<Option<(bundle::Bundle, Bytes)>, crate::Error> {
        match self
            .filter_engine
            .exec(filter::Hook::Originate, bundle, data, self.key_provider())
            .await
            .inspect_err(|_e| {
                error!("Originate filter execution failed");
            })? {
            filter::ExecResult::Continue(_mutation, bundle, data) => Ok(Some((bundle, data))),
            filter::ExecResult::Drop(_bundle, _reason) => Ok(None),
        }
    }

    /// Dispatch a payload from a segment stream (for the Application trait).
    ///
    /// Accumulates the stream (bounded by `max_bundle_size`, like the other
    /// doors) before building: canonical CBOR needs the payload's definite
    /// length up front, so the ADU is whole before the bundle exists. A
    /// producer that goes away before the final segment cancels the send:
    /// nothing has been stored, and the caller gets
    /// [`StreamCancelled`](services::Error::StreamCancelled).
    #[cfg_attr(feature = "instrument", instrument(skip(self, stream)))]
    pub async fn local_dispatch(
        self: &Arc<Self>,
        source: Eid,
        destination: Eid,
        lifetime: Duration,
        flags: Option<services::SendOptions>,
        size_hint: Option<u64>,
        stream: &mut dyn Receiver<Segment>,
    ) -> Result<Id, services::Error> {
        let payload = concat_stream(stream, self.max_bundle_size, size_hint).await?;

        // Build bundle and run Originate filter before storing
        loop {
            let mut builder =
                hardy_bpv7::builder::Builder::new(source.clone(), destination.clone())
                    .with_lifetime(lifetime);

            // Set flags
            if let Some(flags) = &flags {
                builder = builder.with_flags(hardy_bpv7::bundle::Flags {
                    do_not_fragment: flags.do_not_fragment,
                    app_ack_requested: flags.request_ack,
                    report_status_time: flags.report_status_time,
                    receipt_report_requested: flags.notify_reception,
                    forward_report_requested: flags.notify_forwarding,
                    delivery_report_requested: flags.notify_delivery,
                    delete_report_requested: flags.notify_deletion,
                    ..Default::default()
                });

                if flags.notify_reception
                    || flags.notify_forwarding
                    || flags.notify_delivery
                    || flags.notify_deletion
                {
                    builder =
                        builder.with_report_to(self.node_ids.get_admin_endpoint(&destination));
                }
            }

            let (raw, data) = builder
                .with_payload(alloc::borrow::Cow::Borrowed(&payload))
                .build(hardy_bpv7::creation_timestamp::CreationTimestamp::now())
                .map_err(|e| services::Error::Internal(e.into()))?;

            let data = Bytes::from(data);
            let bundle = crate::bundle::parse::rich_from_built(raw, &data)
                .map_err(|e| services::Error::Internal(e.into()))?;

            let r = self.originate_bundle(bundle, data).await;
            if !matches!(r, Err(services::Error::DuplicateBundle)) {
                break r;
            }

            debug!("Duplicate bundle generated by builder, retrying with new timestamp");
        }
    }

    /// Dispatch a bundle from a segment stream (for low-level Service trait).
    ///
    /// Accumulates the stream (bounded by `max_bundle_size`, like CLA
    /// ingress), then parses and validates the assembled bundle (security
    /// boundary - services are not trusted). A producer that goes away
    /// before the final segment cancels the send: nothing has been stored,
    /// and the caller gets
    /// [`StreamCancelled`](services::Error::StreamCancelled).
    #[cfg_attr(feature = "instrument", instrument(skip(self, stream)))]
    pub async fn local_dispatch_raw(
        self: &Arc<Self>,
        expected_source: &Eid,
        stream: &mut dyn Receiver<Segment>,
    ) -> Result<Id, services::Error> {
        let data = concat_stream(stream, self.max_bundle_size, None).await?;

        // Parse + validate the bundle (security boundary — can't trust
        // service-provided bytes). Non-canonical input is rejected, not rewritten;
        // the bytes are stored and forwarded as received. As the origin we must be
        // able to process HopCount / unclocked BundleAge, so an undecryptable one
        // is fatal.
        let (bundle, nokey) =
            crate::bundle::parse::parse_validate_with_provider(data.clone(), self.key_provider())?;
        crate::bundle::parse::reject_undecryptable_liveness(
            &nokey,
            bundle.id.timestamp.is_clocked(),
        )?;

        // Verify source matches the registered service endpoint
        // (registration already validated that the EID belongs to our node)
        if &bundle.id.source != expected_source {
            return Err(services::Error::InvalidSource(bundle.id.source.clone()));
        }

        self.originate_bundle(bundle, data).await
    }

    async fn originate_bundle(
        self: &Arc<Self>,
        bundle: bundle::Bpv7Bundle,
        data: Bytes,
    ) -> Result<Id, services::Error> {
        // Wrap in bundle::Bundle with Dispatching status so that restart
        // recovery skips the Ingress filter (originated bundles only run the
        // Originate filter, never the Ingress filter).
        let bundle = bundle::Bundle {
            metadata: bundle::BundleMetadata {
                status: bundle::BundleStatus::Dispatching,
                ..Default::default()
            },
            bundle,
        };

        // Run Originate filter (pure in-memory)
        let Some((mut bundle, data)) = self
            .run_originate_filter(bundle, data)
            .await
            .inspect_err(|e| error!("Originate filter error: {e}"))?
        else {
            return Err(services::Error::Dropped(None));
        };

        // Now store (single persist operation, preserves filter-modified metadata)
        if !self.store.store(&mut bundle, &data).await {
            return Err(services::Error::DuplicateBundle);
        }

        metrics::counter!("bpa.bundle.originated").increment(1);
        metrics::counter!("bpa.bundle.originated.bytes").increment(data.len() as u64);

        let bundle_id = bundle.bundle.id.clone();
        metrics::gauge!("bpa.bundle.status", "state" => crate::otel_metrics::status_label(&bundle.metadata.status)).increment(1.0);
        self.dispatch_bundle(bundle).await;
        Ok(bundle_id)
    }

    #[cfg_attr(feature = "instrument", instrument(skip(self, bundle),fields(bundle.id = %bundle.bundle.id)))]
    pub(super) async fn deliver_bundle(
        self: &Arc<Self>,
        service: Arc<services::registry::Service>,
        bundle: bundle::Bundle,
    ) {
        let Some((bundle, data)) = self.load_data_or_drop(bundle).await else {
            return;
        };

        // Deliver filter hook, on the processing-pool permit this
        // dispatch task holds.
        let (bundle, data) = match self
            .filter_engine
            .exec(filter::Hook::Deliver, bundle, data, self.key_provider())
            .await
        {
            Ok(filter::ExecResult::Continue(_, bundle, data)) => (bundle, data),
            Ok(filter::ExecResult::Drop(bundle, reason)) => match reason {
                Some(reason) => return self.drop_bundle(bundle, reason).await,
                None => return self.delete_bundle(bundle).await,
            },
            Err(e) => {
                error!("Deliver filter execution failed: {e}");
                return;
            }
        };

        // Resolve the payload the component receives, still on the
        // permit: the raw bundle for a low-level service, or the decoded
        // (and, if BPSec-protected, decrypted) payload for an
        // application.
        let payload = match &service.service {
            services::registry::ServiceImpl::LowLevel(_) => data,
            services::registry::ServiceImpl::Application(_) => {
                // KeyProvider needs a &Bundle; scope the parse as a match
                // expression so the parse OperationSets (which contain
                // `Rc<…>` and are therefore `!Send`) are dropped at the
                // arm boundary, before any `.await` in this async fn.
                // Consume `data` into the parse and work from the
                // authoritative buffer it returns, converting the payload
                // to an owned `Bytes` (zero-copy for the unencrypted case
                // via `slice_ref`) before the arm ends.
                let payload_result = match hardy_bpv7::parse::parse(data) {
                    Ok(hardy_bpv7::parse::Parsed {
                        data: buf,
                        bundle: raw,
                        bcbs: bcb_ops,
                        ..
                    }) => {
                        let key_source = self.key_source(&raw, &buf);
                        match hardy_bpv7::bpsec::block_data(
                            1,
                            &raw.blocks,
                            &buf,
                            &bcb_ops,
                            &*key_source,
                        ) {
                            Ok(hardy_bpv7::block::Payload::Borrowed(s)) => Ok(buf.slice_ref(s)),
                            Ok(hardy_bpv7::block::Payload::Decrypted(d)) => {
                                Ok(Bytes::from_owner(d))
                            }
                            Err(e) => Err(e),
                        }
                    }
                    Err(e) => Err(e),
                };
                match payload_result {
                    Err(hardy_bpv7::Error::InvalidBPSec(hardy_bpv7::bpsec::Error::NoKey)) => {
                        // No key today: park the bundle, a later
                        // registration may collect once keys arrive.
                        debug!("Failed to decrypt payload: No valid keys");
                        return self.store.watch_bundle(bundle).await;
                    }
                    Err(e) => {
                        debug!("Received an invalid payload: {e}");
                        return self
                            .drop_bundle(bundle, ReasonCode::BlockUnintelligible)
                            .await;
                    }
                    Ok(payload) => payload,
                }
            }
        };

        // Park the bundle before announcing it. `on_deliver` returns
        // only when the component has received it (a wire bridge holds
        // the call open across the client's collection window), and it
        // is durably WaitingForService for that whole window, so a
        // session that ends with the delivery still held leaves the
        // bundle already parked for the next registration instead of
        // racing an unregister-time status write. It is parked under the
        // service's registration EID, the exact key
        // `poll_service_waiting` matches on re-registration: the bundle's
        // own destination can be a different Eid variant for the same
        // endpoint (LegacyIpn vs Ipn) and would never match. The swap is
        // conditional, so losing the bundle to a concurrent resolution
        // (the reaper, a duplicate) simply ends the delivery.
        //
        // The id joins `deliveries_in_flight` before the park so that a
        // registration poll snapshotting the parked state always sees the
        // marker and cannot claim the bundle into a second, concurrent
        // delivery; it leaves the set only once this delivery has resolved
        // the bundle or re-parked it for a later poll.
        let service_eid = self
            .node_ids
            .resolve_eid(&service.service_id)
            .unwrap_or_else(|_| bundle.bundle.destination.clone());
        let mut bundle = bundle;
        self.deliveries_in_flight
            .lock()
            .insert(bundle.bundle.id.clone());
        if !self
            .store
            .swap_status(
                &mut bundle,
                &bundle::BundleStatus::WaitingForService {
                    service: service_eid,
                },
            )
            .await
        {
            self.deliveries_in_flight.lock().remove(&bundle.bundle.id);
            return;
        }

        // The whole payload is in hand, so it travels as a single Final
        // segment. Delivery is run off this dispatch task: awaiting it
        // here would pin the shared processing-pool permit for the whole
        // collection window. One detached task per in-flight delivery,
        // bounded by the delivered-but-uncollected set, raced against the
        // registration cancel token so unregister ends it.
        let dispatcher = self.clone();
        let cancel = service.cancel.clone();
        hardy_async::spawn!(self.tasks, "deliver", async move {
            let mut payload = payload;
            let id = bundle.bundle.id.clone();
            let expiry = bundle.expiry();
            let deliver = async {
                match &service.service {
                    services::registry::ServiceImpl::LowLevel(svc) => {
                        svc.on_deliver(&id, expiry, payload.len() as u64, &mut payload)
                            .await
                    }
                    services::registry::ServiceImpl::Application(app) => {
                        app.on_deliver(
                            &id,
                            expiry,
                            bundle.bundle.flags.app_ack_requested,
                            payload.len() as u64,
                            &mut payload,
                        )
                        .await
                    }
                }
            };
            // Completion is polled first so a delivery that finished in the
            // same instant an unregister landed is honoured rather than
            // discarded and re-announced as a duplicate; a pending delivery
            // still yields to the cancel immediately.
            let result = select_biased! {
                r = deliver.fuse() => r,
                _ = cancel.cancelled().fuse() => Err(services::Error::StreamCancelled),
            };

            match result {
                Err(e) => {
                    // The bundle is already parked as WaitingForService;
                    // register it for reaping and re-announcement.
                    debug!("Service delivery deferred: {e}");
                    dispatcher.store.watch_bundle(bundle).await;
                }
                Ok(()) => {
                    // Claim the parked bundle for deletion: the reaper may
                    // have expired it during the collection window, so
                    // completion is conditional and only the winner reports
                    // and deletes.
                    if dispatcher.store.tombstone_if(&bundle).await {
                        metrics::counter!("bpa.bundle.delivered").increment(1);
                        dispatcher.report_bundle_delivery(&bundle).await;

                        // Don't use drop_bundle() as we do not want to count the Drop as a 'dropped bundle'
                        dispatcher
                            .report_bundle_deletion(&bundle, ReasonCode::NoAdditionalInformation)
                            .await;
                        dispatcher.delete_bundle(bundle).await;
                    }
                }
            }
            dispatcher.deliveries_in_flight.lock().remove(&id);
        });
    }
}
