use core::time::Duration;

use alloc::borrow::Cow;

// `Bpv7Bundle` disambiguates the structural wire bundle from the BPA
// record `bundle::Bundle` used throughout this module.
use hardy_bpv7::{
    builder::Builder,
    bundle::{Bundle as Bpv7Bundle, Flags, Id},
    creation_timestamp::CreationTimestamp,
    status_report::ReasonCode,
};

use super::*;
use crate::{
    bundle::parse,
    stream::{ConcatError, Receiver, Segment, concat_stream},
};

impl Dispatcher {
    #[cfg_attr(feature = "instrument", instrument(skip(self, payload)))]
    pub async fn local_dispatch(
        self: &Arc<Self>,
        source: Eid,
        destination: Eid,
        payload: Bytes,
        lifetime: Duration,
        flags: Option<services::SendOptions>,
    ) -> Result<Id, services::Error> {
        // Build bundle and run the Originate chain before storing
        loop {
            let mut builder =
                Builder::new(source.clone(), destination.clone()).with_lifetime(lifetime);

            // Set flags
            if let Some(flags) = &flags {
                builder = builder.with_flags(Flags {
                    do_not_fragment: flags.do_not_fragment,
                    app_ack_requested: flags.request_ack,
                    report_status_time: flags.report_status_time,
                    receipt_report_requested: flags.notify_reception,
                    forward_report_requested: flags.notify_forwarding,
                    delivery_report_requested: flags.notify_delivery,
                    delete_report_requested: flags.notify_deletion,
                    ..Default::default()
                });

                if flags.notify_reception
                    || flags.notify_forwarding
                    || flags.notify_delivery
                    || flags.notify_deletion
                {
                    builder =
                        builder.with_report_to(self.node_ids.get_admin_endpoint(&destination));
                }
            }

            let (bundle, data) = builder
                .with_payload(Cow::Borrowed(&payload))
                .build(CreationTimestamp::now())
                .map_err(|e| services::Error::Internal(e.into()))?;

            let data = Bytes::from(data);
            let extracted = parse::extract_from_built(&bundle, &data)
                .map_err(|e| services::Error::Internal(e.into()))?;

            let r = self.originate_bundle(bundle, extracted, data).await;
            if !matches!(r, Err(services::Error::DuplicateBundle)) {
                break r;
            }

            debug!("Duplicate bundle generated by builder, retrying with new timestamp");
        }
    }

    /// Dispatch a bundle from a segment stream (for low-level Service trait)
    ///
    /// Accumulates the stream (bounded by `max_bundle_size`, like CLA
    /// ingress), then parses and validates the assembled bundle exactly as
    /// [`local_dispatch_raw`](Self::local_dispatch_raw) does. A producer that
    /// goes away before the final segment cancels the send: nothing has been
    /// stored, and the caller gets
    /// [`StreamCancelled`](services::Error::StreamCancelled).
    #[cfg_attr(feature = "instrument", instrument(skip(self, stream)))]
    pub async fn local_dispatch_raw_streamed(
        self: &Arc<Self>,
        expected_source: &Eid,
        stream: &mut dyn Receiver<Segment>,
    ) -> Result<Id, services::Error> {
        // 32-bit: a cap beyond the address space saturates — nothing larger
        // could be buffered anyway.
        let max_size = usize::try_from(self.max_bundle_size.get()).unwrap_or(usize::MAX);
        let data = concat_stream(stream, max_size).await.map_err(|e| match e {
            ConcatError::Cancelled => services::Error::StreamCancelled,
            ConcatError::TooLarge { size, max } => services::Error::PayloadTooLarge { size, max },
        })?;
        self.local_dispatch_raw(expected_source, data).await
    }

    /// Dispatch a bundle from raw bytes (for low-level Service trait)
    /// Parses and validates the bundle (security boundary)
    #[cfg_attr(feature = "instrument", instrument(skip(self, data)))]
    pub async fn local_dispatch_raw(
        self: &Arc<Self>,
        expected_source: &Eid,
        data: Bytes,
    ) -> Result<Id, services::Error> {
        // Parse + validate the bundle (security boundary — can't trust
        // service-provided bytes). Non-canonical input is rejected, not rewritten;
        // the bytes are stored and forwarded as received. As the origin we must be
        // able to process HopCount / unclocked BundleAge, so an undecryptable one
        // is fatal.
        let (bundle, extracted, nokey) =
            parse::parse_validate_with_provider(data.clone(), self.key_provider())?;
        parse::reject_undecryptable_liveness(&nokey, bundle.primary.id.timestamp.is_clocked())?;

        // Verify source matches the registered service endpoint
        // (registration already validated that the EID belongs to our node)
        if &bundle.primary.id.source != expected_source {
            return Err(services::Error::InvalidDestination(
                bundle.primary.id.source.clone(),
            ));
        }

        self.originate_bundle(bundle, extracted, data).await
    }

    async fn originate_bundle(
        self: &Arc<Self>,
        bundle: Bpv7Bundle,
        extensions: bundle::ExtensionFields,
        data: Bytes,
    ) -> Result<Id, services::Error> {
        // Wrap in bundle::Bundle with Dispatching status so that restart
        // recovery skips the Ingress chain (originated bundles only run the
        // Originate chain, never the Ingress chain).
        let mut metadata = bundle::BundleMetadata::originated();
        metadata.extensions = extensions;
        let bundle = bundle::Bundle {
            bpv7: bundle,
            metadata,
            status: bundle::BundleStatus::Dispatching,
        };

        // Inline lifetime/hop admission check for the raw-bytes path: the
        // Builder cannot produce an expired or hop-exhausted bundle, but
        // parse-validated service bytes can — the origination-side twin of
        // ingress's pre-drain gate. Nothing is stored yet, so a rejection
        // is purely an error to the caller.
        if bundle.has_expired() {
            return Err(services::Error::Dropped(Some(ReasonCode::LifetimeExpired)));
        }
        if let Some(hop_info) = &bundle.metadata.extensions.hop_count
            && hop_info.count > hop_info.limit
        {
            return Err(services::Error::Dropped(Some(ReasonCode::HopLimitExceeded)));
        }

        // Run the Originate chain (pure in-memory, pre-store); a Drop
        // returns its reason to the originating service.
        let (mut bundle, data) = match self
            .filters
            .run_originate(bundle, data, &*self.key_provider)
        {
            Ok(filter::ChainOutcome::Continue(bundle, data)) => (bundle, data),
            Ok(filter::ChainOutcome::Drop(_, reason)) => {
                return Err(services::Error::Dropped(reason));
            }
            Err((_, e)) => {
                error!("Originate filter chain failed: {e}");
                return Err(services::Error::Internal(e));
            }
        };

        // Now store (single persist operation, preserves filter-applied metadata)
        if !self.store.store(&mut bundle, &data).await {
            return Err(services::Error::DuplicateBundle);
        }

        metrics::counter!("bpa.bundle.originated").increment(1);
        metrics::counter!("bpa.bundle.originated.bytes").increment(data.len() as u64);

        let bundle_id = bundle.id().clone();
        metrics::gauge!("bpa.bundle.status", "state" => crate::otel_metrics::status_label(&bundle.status)).increment(1.0);
        self.dispatch_bundle(bundle).await;
        Ok(bundle_id)
    }
}
