#!/bin/bash
# Comprehensive lcov coverage collection for Hardy
#
# Unit coverage is measured locally (cargo llvm-cov). Fuzz coverage is read from
# the CFLite-published reports on GitHub Pages — the same numbers shown on the
# coverage dashboard — so no nightly toolchain, corpus checkout, or replay is
# needed. Requires curl + python3 for the fuzz figures.
#
# Usage:
#   ./run_lcov.sh              # Unit (local) + fuzz (from GitHub Pages)
#   ./run_lcov.sh --unit-only  # Skip fuzz coverage (faster)
#
# Published fuzz coverage is read (per target) from:
#   https://ricktaylor.github.io/hardy-fuzz-corpus/coverage/latest/fuzzer_stats/<target>.json
# Override the base with HARDY_COVERAGE_URL=https://.../coverage/latest.
#
# Output:
#   lcov-results.txt           # Summary of all coverage runs
#   docs/coverage_summary.md   # Committed, generated coverage table
#   lcov-*.info                # Per-crate unit lcov files (removed at the end)

set -euo pipefail

cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"

RESULTS_FILE="lcov-results.txt"
UNIT_ONLY=false
FUZZ_UNAVAILABLE=0
FUZZ_TOOLS_MISSING=false

# Base URL of the CFLite-published coverage on GitHub Pages (the fuzz source).
# Override with HARDY_COVERAGE_URL.
COVERAGE_URL_BASE="${HARDY_COVERAGE_URL:-https://ricktaylor.github.io/hardy-fuzz-corpus/coverage/latest}"

usage() {
    cat <<EOF
Usage: $(basename "$0") [--unit-only]

Collects unit test coverage locally (cargo llvm-cov + lcov) and reads fuzz
coverage from the CFLite-published reports on GitHub Pages.

Options:
  --unit-only   Skip fuzz coverage (faster; no network access needed)
  -h, --help    Show this help
EOF
}

for arg in "$@"; do
    case "$arg" in
        --unit-only) UNIT_ONLY=true ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $arg" >&2; usage >&2; exit 2 ;;
    esac
done

# Generate the committed, machine-owned coverage summary from a results file.
# This is the single source of current coverage figures — per-crate reports link
# to it rather than hand-embedding numbers (which drift).
write_coverage_summary() {
    local src="$1" out="docs/coverage_summary.md"
    [ -f "$src" ] || return 0
    {
        echo "# Hardy Coverage Summary"
        echo
        echo "_Generated by \`scripts/run_lcov.sh\` — do not edit by hand._"
        echo
        echo "Run: $(grep -m1 '^Hardy Coverage Report' "$src" | sed 's/^Hardy Coverage Report — //')"
        echo
        echo "Live coverage dashboards: CFLite fuzz coverage at <https://ricktaylor.github.io/hardy-fuzz-corpus/coverage/latest/report/index.html> (CI-published unit + fuzz coverage planned)."
        echo
        echo "## Unit test line coverage"
        echo
        echo "| Crate | Lines | Functions |"
        echo "| :--- | :--- | :--- |"
        awk '
            /^=== UNIT TEST COVERAGE ===/ {s=1; next}
            /^=== FUZZ COVERAGE ===/ {s=0}
            s && /^--- / {n=$0; gsub(/^--- | ---$/,"",n); next}
            s && /lines\.\.\.\.\.\.:/ {l=$0; sub(/.*lines\.\.\.\.\.\.: /,"",l)}
            s && /functions\.\.:/ {f=$0; sub(/.*functions\.\.: /,"",f); if(n!=""){printf "| %s | %s | %s |\n", n, l, f; n=""}}
        ' "$src"
        echo
        echo "## Fuzz line coverage (CFLite, published to GitHub Pages)"
        echo
        echo "| Target | Lines | Functions |"
        echo "| :--- | :--- | :--- |"
        awk '
            /^=== FUZZ COVERAGE ===/ {s=1; next}
            s && /^--- / {n=$0; gsub(/^--- | ---$/,"",n); next}
            s && /lines\.\.\.\.\.\.:/ {l=$0; sub(/.*lines\.\.\.\.\.\.: /,"",l)}
            s && /functions\.\.:/ {f=$0; sub(/.*functions\.\.: /,"",f); if(n!=""){printf "| %s | %s | %s |\n", n, l, f; n=""}}
        ' "$src"
    } > "$out"
    echo "Coverage summary written to $out"
}

echo "Hardy Coverage Report — $(date)" > "$RESULTS_FILE"
echo "==========================================" >> "$RESULTS_FILE"
echo "" >> "$RESULTS_FILE"

# --- Unit test coverage ---

UNIT_CRATES=(
    hardy-cbor
    hardy-bpv7
    hardy-eid-patterns
    hardy-bpa
    hardy-proto
    hardy-tcpclv4
    hardy-otel
    hardy-async
    hardy-ipn-legacy-filter
    hardy-tvr
    hardy-sqlite-storage
    hardy-localdisk-storage
    hardy-bpa-server
    hardy-tcpclv4-server
)

echo "=== UNIT TEST COVERAGE ===" | tee -a "$RESULTS_FILE"
echo "" | tee -a "$RESULTS_FILE"

for crate in "${UNIT_CRATES[@]}"; do
    echo "--- $crate ---" | tee -a "$RESULTS_FILE"
    if cargo llvm-cov test --package "$crate" --lcov --output-path "lcov-${crate}.info" 2>&1; then
        lcov --summary "lcov-${crate}.info" 2>&1 | tee -a "$RESULTS_FILE" \
            || echo "  FAILED — lcov summary error" | tee -a "$RESULTS_FILE"
    else
        echo "  FAILED — see output above" | tee -a "$RESULTS_FILE"
    fi
    echo "" | tee -a "$RESULTS_FILE"
done

if [ "$UNIT_ONLY" = true ]; then
    echo "Skipping fuzz coverage (--unit-only)" | tee -a "$RESULTS_FILE"
    write_coverage_summary "$RESULTS_FILE"
    echo ""
    echo "Results saved to $RESULTS_FILE"
    exit 0
fi

# --- Fuzz coverage ---

echo "=== FUZZ COVERAGE ===" | tee -a "$RESULTS_FILE"
echo "" | tee -a "$RESULTS_FILE"

# Derive fuzz targets from the fuzz crates themselves: the [[bin]] entries in
# each */fuzz/Cargo.toml are the single source of truth, so there is no
# hand-maintained list to drift (.clusterfuzzlite/build.sh derives the same way).
FUZZ_TARGETS=()
for fuzz_dir in */fuzz; do
    [ -d "$fuzz_dir/fuzz_targets" ] || continue
    crate_dir="${fuzz_dir%/fuzz}"
    while IFS= read -r target; do
        [ -n "$target" ] && FUZZ_TARGETS+=("${crate_dir}:${target}")
    done < <(awk -F'"' '/^\[\[bin\]\]/{b=1;next} b&&/name *=/{print $2; b=0}' "$fuzz_dir/Cargo.toml")
done

# Read each target's line/function coverage from the CFLite-published report on
# GitHub Pages (fuzzer_stats/<target>.json — a full llvm-cov export). Filter to
# the fuzzed crate's own src/ and emit lcov-summary-style lines so
# write_coverage_summary parses them like any other run.
fuzz_coverage_from_ghpages() {
    echo "Source: ${COVERAGE_URL_BASE} (CFLite-published)" | tee -a "$RESULTS_FILE"
    echo "" | tee -a "$RESULTS_FILE"

    if ! command -v curl >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
        echo "ERROR: reading published fuzz coverage needs 'curl' and 'python3' — fuzz section skipped" | tee -a "$RESULTS_FILE"
        FUZZ_TOOLS_MISSING=true
        return 0
    fi

    # Sum lines/functions over just this crate's source files in the export
    # JSON. Files are matched by the "/<crate_dir>/src/" path fragment rather
    # than an absolute prefix, so the CFLite container's checkout location
    # doesn't matter.
    local summ_py
    summ_py="$(mktemp)"
    cat > "$summ_py" <<'PY'
import sys, json
needle = sys.argv[1]  # "/<crate_dir>/src/"
files = json.load(sys.stdin)["data"][0]["files"]
lc = lt = fc = ft = 0
for f in files:
    if needle in f["filename"]:
        s = f["summary"]
        lc += s["lines"]["covered"];     lt += s["lines"]["count"]
        fc += s["functions"]["covered"]; ft += s["functions"]["count"]
if lt == 0:
    sys.exit(2)  # no matching source files — treat as unavailable
lp = 100.0 * lc / lt
fp = 100.0 * fc / ft if ft else 0.0
print("  lines......: %.1f%% (%d of %d lines)" % (lp, lc, lt))
print("  functions..: %.1f%% (%d of %d functions)" % (fp, fc, ft))
PY

    local entry crate_dir target url json out
    for entry in "${FUZZ_TARGETS[@]}"; do
        crate_dir="${entry%%:*}"
        target="${entry##*:}"
        url="${COVERAGE_URL_BASE}/fuzzer_stats/${target}.json"
        echo "--- ${crate_dir}/fuzz: ${target} ---" | tee -a "$RESULTS_FILE"

        if ! json="$(curl -fsSL "$url" 2>/dev/null)"; then
            # A target defined in-tree but absent from the published run (e.g. the
            # coverage replay failed for it) must show loudly, not vanish.
            echo "  lines......: UNAVAILABLE (no published coverage)" | tee -a "$RESULTS_FILE"
            echo "  functions..: UNAVAILABLE" | tee -a "$RESULTS_FILE"
            echo "  (no report at ${url})" | tee -a "$RESULTS_FILE"
            FUZZ_UNAVAILABLE=$(( FUZZ_UNAVAILABLE + 1 ))
        elif out="$(printf '%s' "$json" | python3 "$summ_py" "/${crate_dir}/src/" 2>/dev/null)"; then
            printf '%s\n' "$out" | tee -a "$RESULTS_FILE"
        else
            echo "  lines......: UNAVAILABLE (no files matching */${crate_dir}/src/* in report)" | tee -a "$RESULTS_FILE"
            echo "  functions..: UNAVAILABLE" | tee -a "$RESULTS_FILE"
            FUZZ_UNAVAILABLE=$(( FUZZ_UNAVAILABLE + 1 ))
        fi
        echo "" | tee -a "$RESULTS_FILE"
    done

    rm -f "$summ_py"
}

fuzz_coverage_from_ghpages

echo "==========================================" >> "$RESULTS_FILE"
echo "Completed: $(date)" >> "$RESULTS_FILE"

write_coverage_summary "$RESULTS_FILE"

# Clean up lcov files — results are captured in $RESULTS_FILE
rm -f lcov-*.info

echo ""
echo "Results saved to $RESULTS_FILE"

if [ "$FUZZ_TOOLS_MISSING" = true ]; then
    echo ""
    echo "WARNING: fuzz coverage was skipped entirely — 'curl' and/or 'python3' is" >&2
    echo "         not installed. Install both and re-run, or use --unit-only." >&2
fi

if [ "$FUZZ_UNAVAILABLE" -gt 0 ]; then
    echo ""
    echo "WARNING: ${FUZZ_UNAVAILABLE} fuzz target(s) had no usable published coverage" >&2
    echo "         (shown as UNAVAILABLE above and in docs/coverage_summary.md)." >&2
    echo "         The latest CFLite coverage run likely failed for those targets;" >&2
    echo "         re-run the ClusterFuzzLite coverage job to refresh the dashboard." >&2
fi
