[package]
name = "hardy-bpa-api"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
hardy-bpv7 = { path = "../bpv7" }
time = "0.3.36"
async-trait = "0.1.83"
tokio = "1.39.3"
