use alloc::sync::Arc;

use bytes::Bytes;
use hardy_bpv7::bundle::Id as BundleId;
use hardy_bpv7::eid::Eid;
use tracing::debug;

use super::Bpa;
use crate::services;

#[cfg(feature = "instrument")]
use tracing::instrument;

impl Bpa {
    /// Application → BPA: convert SendOptions to Flags, then originate.
    #[cfg_attr(feature = "instrument", instrument(skip(self, payload)))]
    pub async fn local_dispatch(
        self: &Arc<Self>,
        source: Eid,
        destination: Eid,
        payload: Bytes,
        lifetime: core::time::Duration,
        options: Option<services::SendOptions>,
    ) -> Result<BundleId, services::Error> {
        let mut flags = hardy_bpv7::bundle::Flags::default();

        if let Some(opts) = &options {
            flags.do_not_fragment = opts.do_not_fragment;
            flags.app_ack_requested = opts.request_ack;
            flags.report_status_time = opts.report_status_time;
            flags.receipt_report_requested = opts.notify_reception;
            flags.forward_report_requested = opts.notify_forwarding;
            flags.delivery_report_requested = opts.notify_delivery;
            flags.delete_report_requested = opts.notify_deletion;
        }

        loop {
            let r = self
                .originate(source.clone(), destination.clone(), payload.clone(), lifetime, flags)
                .await;
            if !matches!(r, Err(services::Error::DuplicateBundle)) {
                break r;
            }
            debug!("Duplicate bundle generated by builder, retrying with new timestamp");
        }
    }

    /// Low-level Service → BPA: parse raw bundle bytes, validate source, then pipeline.
    #[cfg_attr(feature = "instrument", instrument(skip(self, data)))]
    pub async fn local_dispatch_raw(
        self: &Arc<Self>,
        expected_source: &Eid,
        data: Bytes,
    ) -> Result<BundleId, services::Error> {
        use crate::bundle::{Bundle, BundleMetadata, BundleStatus};
        use crate::ingress::IngressResult;
        use crate::rib::FindResult;

        // Parse and validate (security boundary: services are not trusted)
        let keys = self.key_store.current();
        let checked = hardy_bpv7::bundle::CheckedBundle::parse_with_keys(&data, &**keys)?;

        let (parsed_bundle, data) = if let Some(chunks) = checked.new_data {
            let data = match data.try_into_mut() {
                Ok(buf) => {
                    let mut vec = buf.into();
                    hardy_bpv7::editor::Chunk::flatten_inplace(chunks, &mut vec);
                    Bytes::from(vec)
                }
                Err(original) => {
                    Bytes::from(hardy_bpv7::editor::Chunk::flatten(chunks, &original))
                }
            };
            (checked.bundle, data)
        } else {
            (checked.bundle, data)
        };

        if &parsed_bundle.id.source != expected_source {
            return Err(services::Error::InvalidDestination(
                parsed_bundle.id.source.clone(),
            ));
        }

        let bundle_id = parsed_bundle.id.clone();
        let bundle = Bundle {
            metadata: BundleMetadata {
                status: BundleStatus::Dispatching,
                ..Default::default()
            },
            bundle: parsed_bundle,
        };

        // 1. Ingress
        let (bundle, route) = match self
            .ingress
            .process(bundle, data, Some(crate::filter::Hook::Originate))
            .await
            .map_err(services::Error::Internal)?
        {
            IngressResult::Routed(bundle, route) if route != FindResult::Wait => (bundle, route),
            IngressResult::Routed(_, _) => {
                todo!("handle Wait for originated bundles")
            }
            IngressResult::Duplicate => return Err(services::Error::DuplicateBundle),
            IngressResult::Dropped => return Err(services::Error::Dropped(None)),
        };

        ::metrics::counter!("bpa.bundle.originated").increment(1);

        // 2. Dispatch
        let sink = self.dispatch(&route);

        // 3. Egress
        self.egress.send(bundle, sink.as_ref()).await.ok();
        Ok(bundle_id)
    }

    pub async fn cancel_local_dispatch(&self, bundle_id: &BundleId) -> bool {
        let Some(bundle) = self.store.get_metadata(bundle_id).await else {
            return false;
        };

        self.delete_bundle(bundle).await;
        true
    }
}
