name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get install protobuf-compiler
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
