name: Build, test and E2E
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Use cached dependencies and artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Check formatting
        run: cargo fmt --check

      - name: Build
        run: cargo build --locked --release --all-features --verbose

      - name: Check linting
        run: cargo clippy --locked -- -D warnings

      - name: Test
        run: cargo test --locked --release --all-features --verbose

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-unit-test
    steps:
      - uses: actions/checkout@v6

      - name: Run E2E tests
        run: docker compose -f compose.yaml -f tests/compose.e2e.yml up --build --abort-on-container-exit --exit-code-from e2e-tests

      - name: Cleanup
        if: always()
        run: docker compose -f compose.yaml -f tests/compose.e2e.yml down -v
