name: Documentation

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/user-docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs
        run: pip install mkdocs-material mkdocs-minify-plugin

      - name: Build and deploy
        run: mkdocs gh-deploy --force
