name: Images

on:
  push:
    branches: ["main"]
    tags: ["v*"]
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
      - "**/Dockerfile"
      - ".github/workflows/images.yml"
      - "proto/**"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        include:
          - image: hardy-bpa-server
            dockerfile: ./bpa-server/Dockerfile
            build-args: CARGO_ARGS=--features hardy-bpa-server/sqlite-storage,hardy-bpa-server/postgres-storage,hardy-bpa-server/s3-storage
          - image: hardy-tcpclv4-server
            dockerfile: ./tcpclv4-server/Dockerfile
            build-args: ""
          - image: hardy-tvr
            dockerfile: ./tvr/Dockerfile
            build-args: ""
          - image: hardy-tools
            dockerfile: ./tools/Dockerfile
            build-args: ""

    steps:
      - uses: actions/checkout@v6

      - name: Login to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest

      - name: Build and push with cache
        uses: docker/build-push-action@v7
        with:
          context: "."
          file: ${{ matrix.dockerfile }}
          target: runtime
          build-args: ${{ matrix.build-args }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm64
