name: Rust
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-fmt-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Use cached dependencies and artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Check formatting
        run: cargo fmt --check

      - name: Check linting
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --locked --all-features --verbose

  e2e-tests:
    runs-on: ubuntu-latest
    needs: rust-fmt-lint-test
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Hardy image (cache)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./bpa-server/Dockerfile
          target: runtime
          tags: hardy-bpa-server:latest
          build-args: CARGO_ARGS=--features hardy-bpa-server/sqlite-storage,hardy-bpa-server/postgres-storage
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Build e2e-tests image (cache)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./tests/Dockerfile.tools
          tags: hardy-e2e-tests:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Run E2E tests
        run: docker compose -f compose.yml -f tests/compose.e2e.yml up --no-build --abort-on-container-exit --exit-code-from e2e-tests

      - name: Cleanup
        if: always()
        run: docker compose -f compose.yml -f tests/compose.e2e.yml down -v
